base_dev_dir: '/share/portal/kk837/interact'

data_dir: '${base_dev_dir}/data'

cmu_mocap: '${data_dir}/cmu_mocap'
comad: '${data_dir}/comad_data'
comad_hr: '${data_dir}/comad_data'
synthetic_amass: '${data_dir}/synthetic_amass'

mapping_dir: '${base_dev_dir}/mapping'

mocap_mapping: '${mapping_dir}/mocap_mapping.json'
comad_mapping: '${mapping_dir}/comad_mapping.json'
amass_mapping: '${mapping_dir}/amass_mapping.json'
